ALTER TABLE addresses DROP CONSTRAINT addresses_pkey;
ALTER TABLE addresses DROP COLUMN id;
ALTER TABLE addresses RENAME COLUMN uuid TO id;
ALTER TABLE addresses ADD PRIMARY KEY (id);
ALTER TABLE addresses ALTER COLUMN id SET NOT NULL;

ALTER TABLE authors DROP CONSTRAINT authors_pkey;
ALTER TABLE authors DROP COLUMN id;
ALTER TABLE authors RENAME COLUMN uuid TO id;
ALTER TABLE authors ADD PRIMARY KEY (id);
ALTER TABLE authors ALTER COLUMN id SET NOT NULL;

ALTER TABLE members DROP CONSTRAINT members_pkey;
ALTER TABLE members DROP COLUMN id;
ALTER TABLE members RENAME COLUMN uuid TO id;
ALTER TABLE members ADD PRIMARY KEY (id);
ALTER TABLE members ALTER COLUMN id SET NOT NULL;

ALTER TABLE books DROP CONSTRAINT books_pkey;
ALTER TABLE books DROP COLUMN id;
ALTER TABLE books RENAME COLUMN uuid TO id;
ALTER TABLE books ADD PRIMARY KEY (id);
ALTER TABLE books ALTER COLUMN id SET NOT NULL;

ALTER TABLE copies DROP CONSTRAINT copies_pkey;
ALTER TABLE copies DROP COLUMN id;
ALTER TABLE copies RENAME COLUMN uuid TO id;
ALTER TABLE copies ADD PRIMARY KEY (id);
ALTER TABLE copies ALTER COLUMN id SET NOT NULL;

ALTER TABLE rentals DROP CONSTRAINT rentals_pkey;
ALTER TABLE rentals DROP COLUMN id;
ALTER TABLE rentals RENAME COLUMN uuid TO id;
ALTER TABLE rentals ADD PRIMARY KEY (id);
ALTER TABLE rentals ALTER COLUMN id SET NOT NULL;