ALTER TABLE addresses ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE addresses ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE addresses ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE addresses ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE authors ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE authors ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE authors ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE authors ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE members ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE members ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE members ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE members ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE books ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE books ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE books ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE books ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE copies ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE copies ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE copies ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE copies ADD COLUMN deleted_at TIMESTAMPTZ;

ALTER TABLE rentals ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE rentals ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE rentals ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE rentals ADD COLUMN deleted_at TIMESTAMPTZ;